Sort headers, fix overflowing, copy curl
yiisoft/error-handler pull request #112
Opened 2024-06-22 07:50 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ❌

2024-06-22 07:52 UTC, xepozz commented
<img width="852" alt="image" src="https://github.com/yiisoft/error-handler/assets/6815714/dc216d56-615b-4e5d-910c-65917dec621d">

- Copy button in the curl section
- Sort headers

<img width="806" alt="image" src="https://github.com/yiisoft/error-handler/assets/6815714/cacfa9d3-53b6-48fc-b0fe-166b8f788bb4">

- Fixed long size of the paths / classes

2024-06-22 09:59 UTC, vjik requested changes
Add info to changelog.

2024-06-22 09:59 UTC, vjik commented on src/Renderer/HtmlRenderer.php
> +        if (!empty($request->getBody())) {
Before empty check need to get body as string.

2024-06-22 09:59 UTC, vjik commented on src/Renderer/HtmlRenderer.php
>              return $this->htmlEncode('Error generating curl command: ' . $e->getMessage());
Not need html encode also

2024-06-22 09:59 UTC, vjik commented on templates/development.php
> +            <textarea id="clipboard"><?= $curlInfo ?></textarea>
```suggestion
            <textarea id="clipboard"><?= $this->htmlEncode($curlInfo) ?></textarea>
```

2024-06-24 15:02 UTC, vjik approved these changes

2024-06-24 15:03 UTC, vjik commented on CHANGELOG.md
> +- Enh #112: Add copy cURL button, fix UI (@xepozz)
```suggestion
- Enh #112: Add copy cURL button, sort request headers, fix UI (@xepozz)
```

2024-06-25 06:20 UTC, merged